// eslint-config-next@16 ships native flat configs; spread them directly.
import next from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = [
  ...next,
  ...nextTs,
  {
    // shared/contracts/gen is generated by `buf generate`; don't lint it.
    ignores: [".next/**", "node_modules/**", "dist/**", "shared/contracts/gen/**"],
  },
];

export default eslintConfig;
