// eslint-config-next@16 ships native flat configs; spread them directly.
import next from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = [
  ...next,
  ...nextTs,
  {
    // shared/contracts/gen is generated by `buf generate`; public/mfe holds the
    // built (minified) element-remote bundles — neither is hand-written, don't lint.
    ignores: [".next/**", "node_modules/**", "dist/**", "public/mfe/**", "shared/contracts/gen/**"],
  },
];

export default eslintConfig;
