// Catalogues and policy only — deliberately no cookie, config or `next/headers`
// import. Reading the locale needs the app config (cookie names depend on the
// Secure prefix), and pulling that in here made `npm run i18n:check` boot the
// whole env-validated config just to diff some JSON. The request-scoped lookup
// lives in ./locale.ts instead.
import { pickMessages, type Locale, type MessageSlices, type Messages } from "@evinvest/i18n";
import {
  resolveCatalogue,
  type TranslatedCatalogue,
} from "@evinvest/i18n/policy";

import en from "@/messages/en/common.json";
import ru from "@/messages/ru/common.json";
import vi from "@/messages/vi/common.json";
import fr from "@/messages/fr/common.json";
import de from "@/messages/de/common.json";
import slices from "@/i18n-slices.json";

const AUTHORED: Record<Exclude<Locale, "en">, TranslatedCatalogue> = {
  ru,
  vi,
  fr,
  de,
};

// The translation policy applied once at module scope, not per request:
// `resolveCatalogue` is pure over static input, so the answer is identical for
// every render. A drifted entry falls back to canonical English here exactly as
// it does on the public site — one policy, both surfaces.
const RESOLVED = Object.fromEntries(
  (Object.keys(AUTHORED) as Exclude<Locale, "en">[]).map((locale) => [
    locale,
    resolveCatalogue(locale, en, AUTHORED[locale]),
  ]),
);

export const messagesFor = (locale: Locale): Messages =>
  locale === "en" ? en : (RESOLVED[locale]?.messages ?? en);

/** Per-locale policy outcome — read by `npm run i18n:check`. */
export const catalogueReport = () => Object.values(RESOLVED);


// Slicing: the root provider's `messages` are serialised into every page's RSC
// payload, so handing it the whole resolved catalogue shipped ~1800 strings to a
// page that renders a hundred. `i18n-slices.json` (generated by
// `evinvest-i18n-slices` from the import graph, gated by `i18n:check`) says which
// keys the client tree under each layout and each page actually renders.
//
// English gets no catalogue at all. `t(key, English)` carries the copy at the
// call site, and the registry's translator ignores `messages` for the default
// locale (`source = locale === defaultLocale ? null : messages` in
// @evinvest/i18n's registry.ts) — `I18nScope` short-circuits on it too — so the
// ~1800 English strings it used to serialise into every page were never read.
//
// `satisfies` and not an annotation: the annotation would widen `routes` to
// `Record<string, …>` and a mistyped route would compile.
const SLICES = slices satisfies MessageSlices;

/** A page entry under `app/`, exactly as `i18n-slices.json` keys it. */
export type RouteEntry = keyof typeof SLICES.routes;

// One shared empty object for `en`, from the provider and every scope alike.
const NO_MESSAGES: Messages = Object.freeze({});

/** The root provider's catalogue: what layouts and boundary files render. */
export const shellMessages = (locale: Locale): Messages =>
  locale === "en" ? NO_MESSAGES : pickMessages(messagesFor(locale), SLICES.shell);

/**
 * What a page's `<I18nScope>` lays over the shell. `route` is the page file's
 * own path — `scripts/i18n-scope-check.mts` holds every page to that.
 */
export const routeMessages = (locale: Locale, route: RouteEntry): Messages =>
  locale === "en" ? NO_MESSAGES : pickMessages(messagesFor(locale), SLICES.routes[route]);
