//! gRPC wire contracts for the EV banking hub.
//!
//! The single source of truth for service-to-service communication. The proto
//! files under `proto/banking/v1/` are authored here; `build.rs` compiles them with
//! tonic into client **and** server stubs on every `cargo build`.
//!
//! Consumption:
//! - `piggybank-core` uses the **server** stubs (`banking::v1::*_server`).
//! - `evbanking_auth` uses the `AuthService` stubs to serve its issuance routes.
//! - Other service repos add this crate as a git dependency for the **client**
//!   stubs, and `evbanking_auth` for the verification flow.

/// Generated tonic code for the `banking.v1` proto package (clients + servers +
/// message types), pulled in via `tonic::include_proto!("banking.v1")`.
pub mod banking {
	pub mod v1 {
		// Generated by tonic-build; not ours to lint.
		#![allow(clippy::all, clippy::pedantic)]
		tonic::include_proto!("banking.v1");
	}
}
